Documents/Visual Studio 2013/Projects/listarproy/listarproy/Models/Scheduled.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace listarproy.Models
{
    public class Scheduled
    {
        public int Id { get; set; }
        public DateTime Until { get; set; } 
        public int list { get; set; }
        public int Finished { get; set; }
    }
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Controllers/ScheduledsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using listarproy.Models;

namespace listarproy.Controllers
{
    public class ScheduledsController : Controller
    {
        private listarproyContext db = new listarproyContext();

        // GET: Scheduleds
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Listuser = id.Value;
            try
            {
                ViewBag.Until = DateTime.Now;
                ViewBag.Until = db.Scheduleds.Where(item => item.list == id.Value).Single(item1 => item1.Until == db.Scheduleds.Where(item => item.list == id.Value).Max(item => item.Until)).Until;
                }catch(Exception e){

                }
            return View(db.Scheduleds.Where(item => item.list == id.Value).ToList());
        }

        // GET: Scheduleds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheduled scheduled = db.Scheduleds.Find(id);
            if (scheduled == null)
            {
                return HttpNotFound();
            }
            return View(scheduled);
        }

        // GET: Scheduleds/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Listuser = id.Value;
            return View();
        }

        // POST: Scheduleds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Until,list,Finished")] Scheduled scheduled)
        {
            if (ModelState.IsValid)
            {
                var lists = scheduled.list;
                db.Database.ExecuteSqlCommand(@"UPDATE listas SET Checked=0 WHERE list = {0} ", lists);
                db.Scheduleds.Add(scheduled);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = scheduled.list });
            }

            return View(scheduled);
        }

        // GET: Scheduleds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheduled scheduled = db.Scheduleds.Find(id);
            if (scheduled == null)
            {
                return HttpNotFound();
            }
            return View(scheduled);
        }

        // POST: Scheduleds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Until,list,Finished")] Scheduled scheduled)
        {
            if (ModelState.IsValid)
            {
                db.Entry(scheduled).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = scheduled.list });
            }
            return View(scheduled);
        }

        // GET: Scheduleds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheduled scheduled = db.Scheduleds.Find(id);
            if (scheduled == null)
            {
                return HttpNotFound();
            }
            ViewBag.Listuser = scheduled.list;
            return View(scheduled);
        }

        // POST: Scheduleds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Scheduled scheduled = db.Scheduleds.Find(id);
            db.Scheduleds.Remove(scheduled);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = scheduled.list });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Controllers/listasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using listarproy.Models;

namespace listarproy.Controllers
{
    public class listasController : Controller
    {
        private listarproyContext db = new listarproyContext();
        public int list;
        // GET: listas
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }   ViewBag.ListuserName = db.ListUsers.Find(id).Name;
                ViewBag.Listuser = id.Value;
                try
                {
                    ViewBag.listLength = db.listas.Where(item=>item.list==id).LongCount();
                   var dun=db.Scheduleds.Single(item1 => item1.Until == db.Scheduleds.Max(item => item.Until));
                   if (dun.Until > DateTime.Now)
                   {
                       ViewBag.Until = dun.Id;
                   }
                  
                }catch(Exception e){

                }
                    return View(db.listas.Where(item=>item.list==id).ToList());
        }
      
        // GET: listas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lista lista = db.listas.Find(id);
            if (lista == null)
            {
                return HttpNotFound();
            }
            ViewBag.Listuser = lista.list;
            return View(lista);
        }

        // GET: listas/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Listuser = id.Value;
            return View();
        }

        // POST: listas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,list,Name,Tel,Cel,Email,Otros")] lista lista)
        {
            if (ModelState.IsValid)
            {
                db.listas.Add(lista);
                db.SaveChanges();
                return RedirectToAction("Index", new {id= lista.list });
            }

            return View(lista);
        }

        // GET: listas/Edit/5
        public ActionResult Edit(int? id,int sched,int type)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lista lista = db.listas.Find(id);
            if (lista == null)
            {
                return HttpNotFound();
            }
            ViewBag.sched = sched;
            ViewBag.Listuser = lista.list;
            ViewBag.type = type;
            return View(lista);
        }

        // POST: listas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,list,Tel,Cel,Email,Otros,Checked")] lista lista, int sched, int type)
        {
            if (ModelState.IsValid)
            {
                if (type == 1&&sched!=0) { 
                db.Scheduleds.Find(sched).Finished = db.Scheduleds.Find(sched).Finished + 1;
                } db.Entry(lista).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new {id= lista.list });
            }
            return View(lista);
        }

        // GET: listas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lista lista = db.listas.Find(id);
            if (lista == null)
            {
                return HttpNotFound();
            }
            ViewBag.Listuser = lista.list;
            return View(lista);
        }

        // POST: listas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            lista lista = db.listas.Find(id);
            db.listas.Remove(lista);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = lista.list });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/Scheduleds/Create.cshtml
@model listarproy.Models.Scheduled

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Se programara esta lista para los proximos 7 dias</h4>
        <hr />
       
        @Html.HiddenFor(model => model.Until, new { @Value = DateTime.Now.AddDays(7) })
        @Html.HiddenFor(model => model.list, new { @Value = ViewBag.Listuser })
        @Html.HiddenFor(model => model.Finished, new { @Value = 0 })
            <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aceptar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="buttonboxback">
    @Html.ActionLink("Regresar", "Index", new { id = ViewBag.Listuser })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/Scheduleds/Delete.cshtml
@model listarproy.Models.Scheduled

@{
    ViewBag.Title = "Delete";
}



<h3>Estas seguro de eliminar esta semana programada?</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Until)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Until)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Finished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Finished)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> 
        </div>
    }
</div>
<div class="buttonboxback">
    @Html.ActionLink("Regresar", "Index", new { id = ViewBag.Listuser })
</div>
    

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/Scheduleds/Details.cshtml
@model listarproy.Models.Scheduled

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Scheduled</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Until)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Until)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.list)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.list)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Finished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Finished)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/Scheduleds/Edit.cshtml
@model listarproy.Models.Scheduled

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Scheduled</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Until, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Until, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Until, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.list, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.list, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.list, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Finished, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Finished, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Finished, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/Scheduleds/Index.cshtml
@model IEnumerable<listarproy.Models.Scheduled>

@{
    ViewBag.Title = "Index";
}

<h2>Programa tu semana para generar registros de tus resultados!</h2>
@if (ViewBag.Until < DateTime.Now)
{
    <div class="box">
        @Html.ActionLink("Programa tu semana!", "Create", new { id = ViewBag.Listuser }, new { @style = "color: #000000;" })
        </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Until)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Finished)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Until)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Finished)
            </td>
            <td>
                <div class="rcorners6">
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id })
                </div>
            </td>
        </tr>
    }

</table>
<div class="buttonboxback">
    @Html.ActionLink("Regresar", "Index", "listas", new { Controller = "listas", id = ViewBag.Listuser }, null)
</div>