Documents/Visual Studio 2013/Projects/listarproy/listarproy/Models/lista.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace listarproy.Models
{
    public class lista
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int list { get; set; }
        public int Tel { get; set; }
        public long? Cel { get; set; }
        public String Email { get; set; }
        public String Otros { get; set; }
        public Boolean Checked { get; set; }
    }
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Controllers/ListUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using listarproy.Models;

namespace listarproy.Controllers
{
    public class ListUsersController : Controller
    {
        private listarproyContext db = new listarproyContext();

        // GET: ListUsers
        public ActionResult Index()
        {
            ViewBag.listLength = db.ListUsers.Where(item => item.IdUser == User.Identity.Name).LongCount();
            return View(db.ListUsers.Where(item=>item.IdUser==User.Identity.Name).ToList());
        }

        // GET: ListUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.id = id;
            ListUser listUser = db.ListUsers.Find(id);
            if (listUser == null)
            {
                return HttpNotFound();
            }
            return View(db.ListUsers.Where(item => item.IdUser == User.Identity.Name).ToList());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Details(int? id,int idfrom)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IQueryable<lista> copy = db.listas.Where(item => item.list == idfrom);
          //  int idfinal = db.listas.Max(item => item.Id);
           foreach (lista item in copy)
            {
            //    idfinal++;
              //  item.Id = idfinal;
                item.list = id.Value;
            }
            db.listas.AddRange(copy);
            db.SaveChanges();
            return RedirectToAction("Index");
            

        }
        // GET: ListUsers/Create
        public ActionResult Create(int? id)
        {
            
            return View(id);
        }

        // POST: ListUsers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,IdUser")] ListUser listUser)
        {
            if (ModelState.IsValid)
            {   
                db.ListUsers.Add(listUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(listUser);
        }/*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateCopy([Bind(Include = "Id,Name,IdUser")] ListUser listUser)
        {
            if (ModelState.IsValid)
            {
                db.ListUsers.Add(listUser);
                IQueryable<lista> copy = db.listas.Where(item => item.list == listUser.Id);
                int idfinal = db.listas.Max(item => item.Id);
                foreach(lista item in  copy){
                 idfinal++;
                 item.Id = idfinal;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(listUser);
        }
        */
        // GET: ListUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ListUser listUser = db.ListUsers.Find(id);
            if (listUser == null)
            {
                return HttpNotFound();
            }
            return View(listUser);
        }

        // POST: ListUsers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,IdUser")] ListUser listUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(listUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(listUser);
        }

        // GET: ListUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ListUser listUser = db.ListUsers.Find(id);
            if (listUser == null)
            {
                return HttpNotFound();
            }
            return View(listUser);
        }

        // POST: ListUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ListUser listUser = db.ListUsers.Find(id);
            db.ListUsers.Remove(listUser);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Controllers/ScheduledsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using listarproy.Models;

namespace listarproy.Controllers
{
    public class ScheduledsController : Controller
    {
        private listarproyContext db = new listarproyContext();

        // GET: Scheduleds
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Listuser = id.Value;
            try
            {
                ViewBag.Until = DateTime.Now;
                ViewBag.Until = db.Scheduleds.Where(item => item.list == id.Value).Single(item1 => item1.Until == db.Scheduleds.Where(item => item.list == id.Value).Max(item => item.Until)).Until;
                }catch(Exception e){

                }
            return View(db.Scheduleds.Where(item => item.list == id.Value).ToList());
        }

        // GET: Scheduleds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheduled scheduled = db.Scheduleds.Find(id);
            if (scheduled == null)
            {
                return HttpNotFound();
            }
            return View(scheduled);
        }

        // GET: Scheduleds/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Listuser = id.Value;
            return View();
        }

        // POST: Scheduleds/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Until,list,Finished")] Scheduled scheduled)
        {
            if (ModelState.IsValid)
            {
                var lists = scheduled.list;
                db.Database.ExecuteSqlCommand(@"UPDATE listas SET Checked=0 WHERE list = {0} ", lists);
                db.Scheduleds.Add(scheduled);
                db.SaveChanges();
                return RedirectToAction("Index", new { id = scheduled.list });
            }

            return View(scheduled);
        }

        // GET: Scheduleds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheduled scheduled = db.Scheduleds.Find(id);
            if (scheduled == null)
            {
                return HttpNotFound();
            }
            return View(scheduled);
        }

        // POST: Scheduleds/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Until,list,Finished")] Scheduled scheduled)
        {
            if (ModelState.IsValid)
            {
                db.Entry(scheduled).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = scheduled.list });
            }
            return View(scheduled);
        }

        // GET: Scheduleds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Scheduled scheduled = db.Scheduleds.Find(id);
            if (scheduled == null)
            {
                return HttpNotFound();
            }
            ViewBag.Listuser = scheduled.list;
            return View(scheduled);
        }

        // POST: Scheduleds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Scheduled scheduled = db.Scheduleds.Find(id);
            db.Scheduleds.Remove(scheduled);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = scheduled.list });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Controllers/listasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using listarproy.Models;

namespace listarproy.Controllers
{
    public class listasController : Controller
    {
        private listarproyContext db = new listarproyContext();
        public int list;
        // GET: listas
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }   ViewBag.ListuserName = db.ListUsers.Find(id).Name;
                ViewBag.Listuser = id.Value;
                try
                {
                    ViewBag.listLength = db.listas.Where(item=>item.list==id).LongCount();
                   var dun=db.Scheduleds.Single(item1 => item1.Until == db.Scheduleds.Max(item => item.Until));
                   if (dun.Until > DateTime.Now)
                   {
                       ViewBag.Until = dun.Id;
                   }
                  
                }catch(Exception e){

                }
                    return View(db.listas.Where(item=>item.list==id).ToList());
        }
      
        // GET: listas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lista lista = db.listas.Find(id);
            if (lista == null)
            {
                return HttpNotFound();
            }
            ViewBag.Listuser = lista.list;
            return View(lista);
        }

        // GET: listas/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.Listuser = id.Value;
            return View();
        }

        // POST: listas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,list,Name,Tel,Cel,Email,Otros")] lista lista)
        {
            if (ModelState.IsValid)
            {
                db.listas.Add(lista);
                db.SaveChanges();
                return RedirectToAction("Index", new {id= lista.list });
            }

            return View(lista);
        }

        // GET: listas/Edit/5
        public ActionResult Edit(int? id,int sched,int type)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lista lista = db.listas.Find(id);
            if (lista == null)
            {
                return HttpNotFound();
            }
            ViewBag.sched = sched;
            ViewBag.Listuser = lista.list;
            ViewBag.type = type;
            return View(lista);
        }

        // POST: listas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,list,Tel,Cel,Email,Otros,Checked")] lista lista, int sched, int type)
        {
            if (ModelState.IsValid)
            {
                if (type == 1&&sched!=0) { 
                db.Scheduleds.Find(sched).Finished = db.Scheduleds.Find(sched).Finished + 1;
                } db.Entry(lista).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new {id= lista.list });
            }
            return View(lista);
        }

        // GET: listas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            lista lista = db.listas.Find(id);
            if (lista == null)
            {
                return HttpNotFound();
            }
            ViewBag.Listuser = lista.list;
            return View(lista);
        }

        // POST: listas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            lista lista = db.listas.Find(id);
            db.listas.Remove(lista);
            db.SaveChanges();
            return RedirectToAction("Index", new { id = lista.list });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/listas/Create.cshtml
@model listarproy.Models.lista

@{
    ViewBag.Title = "Create";
}

<h2>Crear contacto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style='clear:both; width: 370px;'>


        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.list, new { @Value = ViewBag.Listuser })
        <div class="form-group">
            Nombre
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Checked, new { @Value = false })
        <div class="form-group">
            Telefono
            <div class="col-md-6">
                @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            Celular
            <div class="col-md-6">
                @Html.EditorFor(model => model.Cel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cel, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            E-mail
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            Otros
            <div class="col-md-6">
                @Html.EditorFor(model => model.Otros, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Otros, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class ="buttonboxback">
    @Html.ActionLink("Regresar", "Index", new { id = ViewBag.Listuser })
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/listas/Delete.cshtml
@model listarproy.Models.lista

@{
    ViewBag.Title = "Delete";
 
}

<h2>Eliminar</h2>

<h3>Estas seguro de eliminar el contacto?</h3>
<div>
   
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nombre:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
           Telefono:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tel)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Eliminar" class="btn btn-default" />
    </div>
    }
</div>
<div class="buttonboxback">
    @Html.ActionLink("Regresar", "Index", new { id = ViewBag.Listuser })
</div>

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/listas/Details.cshtml
@model listarproy.Models.lista

@{
    ViewBag.Title = "Details";
}

                    <h4>@Html.DisplayFor(model => model.Name)</h4>
                    <hr />
                    <dl class="dl-horizontal">

                        <dt>
                          Telefono:
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Tel)
                        </dd>
                        <dt>
                            Otros:
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Otros)
                        </dd>
                        <dt>
                            E-mail:
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Email)
                        </dd>
                        <dt>
                            Celular:
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Cel)
                        </dd>
                    </dl>
     
                
                    <div class="rcorners6">
                        @Html.ActionLink("Editar", "Edit", new { id = Model.Id })</div>
                        <div class="buttonboxback">
                            @Html.ActionLink("Regresar", "Index", new { id = ViewBag.Listuser })
                        </div>

               
    
              

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/listas/Edit.cshtml
@model listarproy.Models.lista

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style='clear:both; width: 370px;'>

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @if (@ViewBag.Type == 0)
        {
            <div class="form-group">
                Nombre<div class="col-md-6">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(model => model.list, new { @Value = ViewBag.Listuser })
            <div class="form-group">
                Telefono<div class="col-md-6">
                    @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tel, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                Celular<div class="col-md-6">
                    @Html.EditorFor(model => model.Cel, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Cel, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                E-mail<div class="col-md-6">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                Otros<div class="col-md-6">
                    @Html.EditorFor(model => model.Otros, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Otros, "", new { @class = "text-danger" })
                </div>
            </div>
            @Html.HiddenFor(model => model.Checked);
                                                   int asd = 0;
                                                   if (ViewBag.sched != null)
                                                   {
                                                       asd = ViewBag.sched;
                                                   }

                                                @Html.HiddenFor(sched => asd)
            if (ViewBag.type != null)
            {
                asd = ViewBag.type;
            }
            @Html.HiddenFor(type => asd)
        }
        else
        {
            <div> Se cambiara el estado a chequeado al guardar</div>

            @Html.HiddenFor(model => model.Name)
            @Html.HiddenFor(model => model.list, new { @Value = ViewBag.Listuser })
            @Html.HiddenFor(model => model.Tel)
            @Html.HiddenFor(model => model.Checked, new { @Value = true })
          @Html.HiddenFor(model => model.Cel)
            @Html.HiddenFor(model => model.Otros)
            @Html.HiddenFor(model => model.Email)
            int asd = 0;
            if (ViewBag.sched != null)
            {
                asd = ViewBag.sched;
            }

            @Html.HiddenFor(sched => asd)
            if (ViewBag.type != null)
            {
                asd = ViewBag.type;
            }
            @Html.HiddenFor(type => asd)
        }


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar cambios" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="buttonboxback">
    @Html.ActionLink("Regresar", "Index", new { id = ViewBag.Listuser })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Documents/Visual Studio 2013/Projects/listarproy/listarproy/Views/listas/Index.cshtml
@model IEnumerable<listarproy.Models.lista>

@{
    ViewBag.Title = "Index";
}

<h2>@ViewBag.ListuserName</h2>


@if (ViewBag.Until != null)
{
    ViewBag.NNUntil = ViewBag.Until;
}
else
{
    ViewBag.NNUntil = 0;
}
@if (ViewBag.listLength == 0)
{
    <div class="box">
        @Html.ActionLink("Crear contacto nuevo", "Create", new { id = ViewBag.Listuser }, new { @style = "color: #000000; " })
    </div>
}
else
{
    <div style='clear:both; width: 370px;'>

        <div class="box" style='float:left'>
            @Html.ActionLink("Crear contacto nuevo", "Create", new { id = ViewBag.Listuser }, new { @style = "color: #000000; " })
        </div>
        <div class="box" style='float:right'>
            @Html.ActionLink("Programar semana!", "Index", "Scheduleds", new { Controller = "Scheduleds", id = ViewBag.Listuser }, new { @style = "color: #000000;" })
        </div>
    </div>



    foreach (var item in Model)
    {
        <div class="tr">

            <ul class="nav navbar-nav">
                <li class="grande">
                    @Html.DisplayFor(wibble => item.Name)
                </li>


                @if (item.Checked == false)
                {
                    <li class="rcorners4">@Html.ActionLink("llamar", "Edit", new { id = item.Id, type = 1, sched = ViewBag.NNUntil })</li>
                }
                else
                {
                    <li><p class="rcorners5"></p></li>
                }
                <li class="rcorners6">@Html.ActionLink("Ver", "Details", new { id = item.Id }) </li>
                <li class="rcorners6">@Html.ActionLink("Editar", "Edit", new { id = item.Id, type = 0, sched = 0 })</li>
                <li class="rcorners6">@Html.ActionLink("Eliminar", "Delete", new { id = item.Id })</li>
            </ul><label>  <br /><br /><br /><br /></label>
        </div>
    }


}
<div class="buttonboxback">
    @Html.ActionLink("Regresar", "Index", "ListUsers")
</div>